This notebook contains the following:
'#01 - Importing Libraries
'#02 - Importing Data
'#03 - Data Cleaning
'#04 - Create New Columns for Playoff Success

# 01 - Import Libraries

In [1]:
# Import Libraries
import pandas as pd
import numpy as np
import os
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib

# 02 - Import Data Sets

In [2]:
# import three data sets
path = r'C:\Users\jakey\OneDrive\Documents\Data Analytics\CareerFoundry\Data Immersion\Achievement 6\Project Folder'

In [3]:
# import playerbio
df_playoffsbio = pd.read_csv(os.path.join(path, '02 Data', 'Prepared Data', 'playoffsbio.csv'), index_col = False)

# 03 - Check DF

In [4]:
df_playoffsbio.head()

,Unnamed: 0,playerId,season,first_name,last_name,team,position,games_played,icetime,gameScore,year,month,day,weight,height,nationality,shootsCatches,primaryNumber,_merge
0,0,8471709,2008,Marc-Edouard,Vlasic,S.J,D,6,7435,0.72,1987,3,30,205,73,CAN,L,44,both
1,1,8471709,2009,Marc-Edouard,Vlasic,S.J,D,15,19701,5.58,1987,3,30,205,73,CAN,L,44,both
2,2,8471709,2010,Marc-Edouard,Vlasic,S.J,D,18,23496,6.10,1987,3,30,205,73,CAN,L,44,both
3,3,8471709,2011,Marc-Edouard,Vlasic,S.J,D,5,6265,-0.10,1987,3,30,205,73,CAN,L,44,both
4,4,8471709,2012,Marc-Edouard,Vlasic,S.J,D,11,13639,2.42,1987,3,30,205,73,CAN,L,44,both

In [5]:
# drop columns
df_playoffsbio = df_playoffsbio.drop(columns = ['Unnamed: 0', '_merge'])

In [6]:
df_playoffsbio.head()

,playerId,season,first_name,last_name,team,position,games_played,icetime,gameScore,year,month,day,weight,height,nationality,shootsCatches,primaryNumber
0,8471709,2008,Marc-Edouard,Vlasic,S.J,D,6,7435,0.72,1987,3,30,205,73,CAN,L,44
1,8471709,2009,Marc-Edouard,Vlasic,S.J,D,15,19701,5.58,1987,3,30,205,73,CAN,L,44
2,8471709,2010,Marc-Edouard,Vlasic,S.J,D,18,23496,6.10,1987,3,30,205,73,CAN,L,44
3,8471709,2011,Marc-Edouard,Vlasic,S.J,D,5,6265,-0.10,1987,3,30,205,73,CAN,L,44
4,8471709,2012,Marc-Edouard,Vlasic,S.J,D,11,13639,2.42,1987,3,30,205,73,CAN,L,44

In [7]:
df_playoffsbio.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5307 entries, 0 to 5306
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   playerId       5307 non-null   int64
 1   season         5307 non-null   int64
 2   first_name     5307 non-null   object
 3   last_name      5307 non-null   object
 4   team           5307 non-null   object
 5   position       5307 non-null   object
 6   games_played   5307 non-null   int64
 7   icetime        5307 non-null   int64
 8   gameScore      4932 non-null   float64
 9   year           5307 non-null   int64
 10  month          5307 non-null   int64
 11  day            5307 non-null   int64
 12  weight         5307 non-null   int64
 13  height         5307 non-null   int64
 14  nationality    5307 non-null   object
 15  shootsCatches  5307 non-null   object
 16  primaryNumber  5307 non-null   int64
dtypes: float64(1), int64(10), object(6)
memory usage: 705.0+ KB

In [8]:
df_playoffsbio.describe

<bound method NDFrame.describe of       playerId  season    first_name last_name team position  games_played  \
0      8471709    2008  Marc-Edouard    Vlasic  S.J        D             6
1      8471709    2009  Marc-Edouard    Vlasic  S.J        D            15
2      8471709    2010  Marc-Edouard    Vlasic  S.J        D            18
3      8471709    2011  Marc-Edouard    Vlasic  S.J        D             5
4      8471709    2012  Marc-Edouard    Vlasic  S.J        D            11
...        ...     ...           ...       ...  ...      ...           ...
5302   8478971    2021        Connor    Ingram  NSH        G             4
5303   8478902    2021          Erik  Kallgren  TOR        G             1
5304   8480382    2021     Alexandar  Georgiev  NYR        G             2
5305   8477361    2021           Cal  Petersen  LAK        G             1
5306   8479193    2021         Casey   DeSmith  PIT        G             1

      icetime  gameScore  year  month  day  weight  height nationality  \
0        7435       0.72  1987      3   30     205      73         CAN
1       19701       5.58  1987      3   30     205      73         CAN
2       23496       6.10  1987      3   30     205      73         CAN
3        6265      -0.10  1987      3   30     205      73         CAN
4       13639       2.42  1987      3   30     205      73         CAN
...       ...        ...   ...    ...  ...     ...     ...         ...
5302    13851        NaN  1997      3   31     196      74         CAN
5303     1846        NaN  1996     10   14     193      75         SWE
5304     3537        NaN  1996      2   10     179      73         RUS
5305     1934        NaN  1994     10   19     185      73         USA
5306     5347        NaN  1991      8   13     181      72         USA

     shootsCatches  primaryNumber
0                L             44
1                L             44
2                L             44
3                L             44
4                L             44
...            ...            ...
5302             L             39
5303             L             50
5304             L             40
5305             R             40
5306             L              1

[5307 rows x 17 columns]>

# 04 - Create New Columns for Playoff Success

In [ ]:
# All Stanley Cup Winners will say Winner
def

In [9]:
df_playoffsbio['team'].value_counts()

PIT    318
WSH    292
BOS    275
NSH    250
STL    249
CHI    231
NYR    224
S.J    222
MTL    210
MIN    202
T.B    188
PHI    187
ANA    187
DET    180
VAN    168
COL    161
L.A    158
TOR    154
NYI    142
CGY    136
CBJ    135
DAL    123
OTT    120
CAR    117
FLA    114
WPG    111
EDM     93
VGK     92
N.J     90
ARI     86
BUF     48
LAK     23
TBL     21
Name: team, dtype: int64

In [10]:
# transform teams - TBL & T.B are the same - LAK & L.A are the same
df_playoffsbio['team'].replace({'T.B': 'TBL', 'L.A': 'LAK', 'N.J': 'NJD', 'S.J': 'SJS'}, inplace=True)

In [11]:
df_playoffsbio['team'].value_counts()

PIT    318
WSH    292
BOS    275
NSH    250
STL    249
CHI    231
NYR    224
SJS    222
MTL    210
TBL    209
MIN    202
PHI    187
ANA    187
LAK    181
DET    180
VAN    168
COL    161
TOR    154
NYI    142
CGY    136
CBJ    135
DAL    123
OTT    120
CAR    117
FLA    114
WPG    111
EDM     93
VGK     92
NJD     90
ARI     86
BUF     48
Name: team, dtype: int64

In [ ]:
#df_playoffsbio['playoffs'] = np.where((df_playoffsbio['season'] == 2021) & (df_playoffsbio['team'] == 'COL'))